import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author EliteBook 840 G3
 */
public class NewJFrame extends javax.swing.JFrame {

    private JLabel jLabel1;
    private JRadioButton redcoff;
    private JRadioButton redtea;
    private JRadioButton redcap;
    private JCheckBox chkbeg;
    private JCheckBox chktoa;
    private JCheckBox chkcroi;
    private JScrollPane jScrollPane1;
    private JTextPane subtex;
    private JScrollPane jScrollPane2;
    private JTextPane tetex;
    private JScrollPane jScrollPane3;
    private JTextPane textot;
    private JLabel txtsub;
    private JLabel txtTax;
    private JLabel txtTot;
    private JButton btnenter;
    private JButton btnclear;
    private JButton btnexist;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        redcoff = new javax.swing.JRadioButton();
        redtea = new javax.swing.JRadioButton();
        redcap = new javax.swing.JRadioButton();
        chkbeg = new javax.swing.JCheckBox();
        chktoa = new javax.swing.JCheckBox();
        chkcroi = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        subtex = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tetex = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        textot = new javax.swing.JTextPane();
        txtsub = new javax.swing.JLabel();
        txtTax = new javax.swing.JLabel();
        txtTot = new javax.swing.JLabel();
        btnenter = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnexist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("coffee shop");

        redcoff.setText(" coffe 2.35");
        redcoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redcoffActionPerformed(evt);
            }
        });

        redtea.setText("tea 1.45");
        redtea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redteaActionPerformed(evt);
            }
        });

        redcap.setText(" cappuccion 3.45");
        redcap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redcapActionPerformed(evt);
            }
        });

        chkbeg.setText(" begals 1.02");
        chkbeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbegActionPerformed(evt);
            }
        });

        chktoa.setText("toast 1.45");

        chkcroi.setText("croissant 2.45");

        jScrollPane1.setViewportView(subtex);

        jScrollPane2.setViewportView(tetex);

        jScrollPane3.setViewportView(textot);

        txtsub.setText("subtotal");

        txtTax.setText("tax");

        txtTot.setText("total");

        btnenter.setText("enter");
        btnenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenterActionPerformed(evt);
            }
        });

        btnclear.setText("clear");

        btnexist.setText("exist");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(redtea, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chktoa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(redcoff)
                                    .addGap(155, 155, 155)
                                    .addComponent(chkbeg, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnexist)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnenter)
                                                .addComponent(btnclear))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(txtTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(txtsub, javax.swing.GroupLayout.Alignment.TRAILING))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane3))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(redcap, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)
                                .addComponent(chkcroi))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(redcoff))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(chkbeg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(redtea)
                    .addComponent(chktoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(redcap)
                    .addComponent(chkcroi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtsub)
                        .addComponent(btnenter)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTax)
                        .addComponent(btnclear)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTot)
                    .addComponent(btnexist))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void redcoffActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // select the coffee option
        if (redcoff.isSelected()) {
            redcap.setEnabled(false);
            redtea.setEnabled(false);
        } else {
            redcap.setEnabled(true);
            redtea.setEnabled(true);
        }
            
    }                                       

    private void redteaActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
         //select the tea option
        if (redtea.isSelected()) {
            redcap.setEnabled(false);
            redcoff.setEnabled(false);
        } else {
            redcap.setEnabled(true);
            redcoff.setEnabled(true);
        }
    }                                      

    private void redcapActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if (redcap.isSelected()) {
            redtea.setEnabled(false);
            redcoff.setEnabled(false);
        } else {
            redtea.setEnabled(true);
            redcoff.setEnabled(true);
        }        // TODO add your handling code here:
    }                                      

    private void chkbegActionPerformed(java.awt.event.ActionEvent evt) {                                       
    }                                      

    private void btnenterActionPerformed(java.awt.event.ActionEvent evt) {                                         
                                        
    double total;
    double subtotal = 0;
    final double TAX_RATE = 0.08; // Use uppercase and underscores for constants
    double tax;

    if (redcoff.isSelected()) {
        subtotal += 2.35;
    } else if (redtea.isSelected()) {
        subtotal += 1.45;
    } else if (redcap.isSelected()) {
        subtotal += 3.45;
    }

    if (chkbeg.isSelected()) {
        subtotal += 1;
    }
    
    if (chktoa.isSelected()) {
        subtotal += 1.45;
    }

    if (chkcroi.isSelected()) {
        subtotal += 2;
    }

    // Calculate tax and total
    tax = subtotal * TAX_RATE;
    total = subtotal + tax;
    }
     txtsub.setText(Double.toString(subtotal));
     
     subtotal=double.parseDouble(txtsub.getText());
     total=tax+subtotal;
     
     txtTax.setText(double.toString(tax));
     txtTot.setText(double.toString(total)); 
    }                                        

   /**
    * @param args the command line arguments
    */
   public static void main(String[] args)
   /* set the nimbus look and feel */
   Look and feel setting code (optional)

   /* create and display the form */
   java.awt.EventQueue.invokelater(new Runnable()) {
      public void run(){ 
            new NewJFrame().setVisible(true);
}


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnenter;
    private javax.swing.JButton btnexist;
    private javax.swing.JCheckBox chkbeg;
    private javax.swing.JCheckBox chkcroi;
    private javax.swing.JCheckBox chktoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton redcap;
    private javax.swing.JRadioButton redcoff;
    private javax.swing.JRadioButton redtea;
    private javax.swing.JTextPane subtex;
    private javax.swing.JTextPane tetex;
    private javax.swing.JTextPane textot;
    private javax.swing.JLabel txtTax;
    private javax.swing.JLabel txtTot;
    private javax.swing.JLabel txtsub;
    // End of variables declaration                   
}
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author EliteBook 840 G3
 */
public class NewJFrame extends javax.swing.JFrame {

    private JLabel jLabel1;
    private JRadioButton redcoff;
    private JRadioButton redtea;
    private JRadioButton redcap;
    private JCheckBox chkbeg;
    private JCheckBox chktoa;
    private JCheckBox chkcroi;
    private JScrollPane jScrollPane1;
    private JTextPane subtex;
    private JScrollPane jScrollPane2;
    private JTextPane tetex;
    private JScrollPane jScrollPane3;
    private JTextPane textot;
    private JLabel txtsub;
    private JLabel txtTax;
    private JLabel txtTot;
    private JButton btnenter;
    private JButton btnclear;
    private JButton btnexist;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        redcoff = new javax.swing.JRadioButton();
        redtea = new javax.swing.JRadioButton();
        redcap = new javax.swing.JRadioButton();
        chkbeg = new javax.swing.JCheckBox();
        chktoa = new javax.swing.JCheckBox();
        chkcroi = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        subtex = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tetex = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        textot = new javax.swing.JTextPane();
        txtsub = new javax.swing.JLabel();
        txtTax = new javax.swing.JLabel();
        txtTot = new javax.swing.JLabel();
        btnenter = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnexist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("coffee shop");

        redcoff.setText(" coffe 2.35");
        redcoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redcoffActionPerformed(evt);
            }
        });

        redtea.setText("tea 1.45");
        redtea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redteaActionPerformed(evt);
            }
        });

        redcap.setText(" cappuccion 3.45");
        redcap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redcapActionPerformed(evt);
            }
        });

        chkbeg.setText(" begals 1.02");
        chkbeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbegActionPerformed(evt);
            }
        });

        chktoa.setText("toast 1.45");

        chkcroi.setText("croissant 2.45");

        jScrollPane1.setViewportView(subtex);

        jScrollPane2.setViewportView(tetex);

        jScrollPane3.setViewportView(textot);

        txtsub.setText("subtotal");

        txtTax.setText("tax");

        txtTot.setText("total");

        btnenter.setText("enter");
        btnenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenterActionPerformed(evt);
            }
        });

        btnclear.setText("clear");

        btnexist.setText("exist");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(redtea, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chktoa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(redcoff)
                                    .addGap(155, 155, 155)
                                    .addComponent(chkbeg, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnexist)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnenter)
                                                .addComponent(btnclear))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(txtTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(txtsub, javax.swing.GroupLayout.Alignment.TRAILING))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane3))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(redcap, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)
                                .addComponent(chkcroi))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(redcoff))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(chkbeg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(redtea)
                    .addComponent(chktoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(redcap)
                    .addComponent(chkcroi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtsub)
                        .addComponent(btnenter)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTax)
                        .addComponent(btnclear)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTot)
                    .addComponent(btnexist))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void redcoffActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // select the coffee option
        if (redcoff.isSelected()) {
            redcap.setEnabled(false);
            redtea.setEnabled(false);
        } else {
            redcap.setEnabled(true);
            redtea.setEnabled(true);
        }
            
    }                                       

    private void redteaActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
         //select the tea option
        if (redtea.isSelected()) {
            redcap.setEnabled(false);
            redcoff.setEnabled(false);
        } else {
            redcap.setEnabled(true);
            redcoff.setEnabled(true);
        }
    }                                      

    private void redcapActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if (redcap.isSelected()) {
            redtea.setEnabled(false);
            redcoff.setEnabled(false);
        } else {
            redtea.setEnabled(true);
            redcoff.setEnabled(true);
        }        // TODO add your handling code here:
    }                                      

    private void chkbegActionPerformed(java.awt.event.ActionEvent evt) {                                       
    }                                      

    private void btnenterActionPerformed(java.awt.event.ActionEvent evt) {                                         
                                        
    double total;
    double subtotal = 0;
    final double TAX_RATE = 0.08; // Use uppercase and underscores for constants
    double tax;

    if (redcoff.isSelected()) {
        subtotal += 2.35;
    } else if (redtea.isSelected()) {
        subtotal += 1.45;
    } else if (redcap.isSelected()) {
        subtotal += 3.45;
    }

    if (chkbeg.isSelected()) {
        subtotal += 1;
    }
    
    if (chktoa.isSelected()) {
        subtotal += 1.45;
    }

    if (chkcroi.isSelected()) {
        subtotal += 2;
    }

    // Calculate tax and total
    tax = subtotal * TAX_RATE;
    total = subtotal + tax;
    }
     txtsub.setText(Double.toString(subtotal));
     
     subtotal=double.parseDouble(txtsub.getText());
     total=tax+subtotal;
     
     txtTax.setText(double.toString(tax));
     txtTot.setText(double.toString(total)); 
    }                                        

   /**
    * @param args the command line arguments
    */
   public static void main(String[] args)
   /* set the nimbus look and feel */
   Look and feel setting code (optional)

   /* create and display the form */
   java.awt.EventQueue.invokelater(new Runnable()) {
      public void run(){ 
            new NewJFrame().setVisible(true);
}


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnenter;
    private javax.swing.JButton btnexist;
    private javax.swing.JCheckBox chkbeg;
    private javax.swing.JCheckBox chkcroi;
    private javax.swing.JCheckBox chktoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton redcap;
    private javax.swing.JRadioButton redcoff;
    private javax.swing.JRadioButton redtea;
    private javax.swing.JTextPane subtex;
    private javax.swing.JTextPane tetex;
    private javax.swing.JTextPane textot;
    private javax.swing.JLabel txtTax;
    private javax.swing.JLabel txtTot;
    private javax.swing.JLabel txtsub;
    // End of variables declaration                   
}
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author EliteBook 840 G3
 */
public class NewJFrame extends javax.swing.JFrame {

    private JLabel jLabel1;
    private JRadioButton redcoff;
    private JRadioButton redtea;
    private JRadioButton redcap;
    private JCheckBox chkbeg;
    private JCheckBox chktoa;
    private JCheckBox chkcroi;
    private JScrollPane jScrollPane1;
    private JTextPane subtex;
    private JScrollPane jScrollPane2;
    private JTextPane tetex;
    private JScrollPane jScrollPane3;
    private JTextPane textot;
    private JLabel txtsub;
    private JLabel txtTax;
    private JLabel txtTot;
    private JButton btnenter;
    private JButton btnclear;
    private JButton btnexist;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        redcoff = new javax.swing.JRadioButton();
        redtea = new javax.swing.JRadioButton();
        redcap = new javax.swing.JRadioButton();
        chkbeg = new javax.swing.JCheckBox();
        chktoa = new javax.swing.JCheckBox();
        chkcroi = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        subtex = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tetex = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        textot = new javax.swing.JTextPane();
        txtsub = new javax.swing.JLabel();
        txtTax = new javax.swing.JLabel();
        txtTot = new javax.swing.JLabel();
        btnenter = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnexist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("coffee shop");

        redcoff.setText(" coffe 2.35");
        redcoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redcoffActionPerformed(evt);
            }
        });

        redtea.setText("tea 1.45");
        redtea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redteaActionPerformed(evt);
            }
        });

        redcap.setText(" cappuccion 3.45");
        redcap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redcapActionPerformed(evt);
            }
        });

        chkbeg.setText(" begals 1.02");
        chkbeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbegActionPerformed(evt);
            }
        });

        chktoa.setText("toast 1.45");

        chkcroi.setText("croissant 2.45");

        jScrollPane1.setViewportView(subtex);

        jScrollPane2.setViewportView(tetex);

        jScrollPane3.setViewportView(textot);

        txtsub.setText("subtotal");

        txtTax.setText("tax");

        txtTot.setText("total");

        btnenter.setText("enter");
        btnenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenterActionPerformed(evt);
            }
        });

        btnclear.setText("clear");

        btnexist.setText("exist");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(redtea, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chktoa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(redcoff)
                                    .addGap(155, 155, 155)
                                    .addComponent(chkbeg, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnexist)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnenter)
                                                .addComponent(btnclear))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(txtTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(txtsub, javax.swing.GroupLayout.Alignment.TRAILING))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane3))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(redcap, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)
                                .addComponent(chkcroi))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(redcoff))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(chkbeg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(redtea)
                    .addComponent(chktoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(redcap)
                    .addComponent(chkcroi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtsub)
                        .addComponent(btnenter)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTax)
                        .addComponent(btnclear)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTot)
                    .addComponent(btnexist))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void redcoffActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // select the coffee option
        if (redcoff.isSelected()) {
            redcap.setEnabled(false);
            redtea.setEnabled(false);
        } else {
            redcap.setEnabled(true);
            redtea.setEnabled(true);
        }
            
    }                                       

    private void redteaActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
         //select the tea option
        if (redtea.isSelected()) {
            redcap.setEnabled(false);
            redcoff.setEnabled(false);
        } else {
            redcap.setEnabled(true);
            redcoff.setEnabled(true);
        }
    }                                      

    private void redcapActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if (redcap.isSelected()) {
            redtea.setEnabled(false);
            redcoff.setEnabled(false);
        } else {
            redtea.setEnabled(true);
            redcoff.setEnabled(true);
        }        // TODO add your handling code here:
    }                                      

    private void chkbegActionPerformed(java.awt.event.ActionEvent evt) {                                       
    }                                      

    private void btnenterActionPerformed(java.awt.event.ActionEvent evt) {                                         
                                        
    double total;
    double subtotal = 0;
    final double TAX_RATE = 0.08; // Use uppercase and underscores for constants
    double tax;

    if (redcoff.isSelected()) {
        subtotal += 2.35;
    } else if (redtea.isSelected()) {
        subtotal += 1.45;
    } else if (redcap.isSelected()) {
        subtotal += 3.45;
    }

    if (chkbeg.isSelected()) {
        subtotal += 1;
    }
    
    if (chktoa.isSelected()) {
        subtotal += 1.45;
    }

    if (chkcroi.isSelected()) {
        subtotal += 2;
    }

    // Calculate tax and total
    tax = subtotal * TAX_RATE;
    total = subtotal + tax;
    }
     txtsub.setText(Double.toString(subtotal));
     
     subtotal=double.parseDouble(txtsub.getText());
     total=tax+subtotal;
     
     txtTax.setText(double.toString(tax));
     txtTot.setText(double.toString(total)); 
    }                                        

   /**
    * @param args the command line arguments
    */
   public static void main(String[] args)
   /* set the nimbus look and feel */
   Look and feel setting code (optional)

   /* create and display the form */
   java.awt.EventQueue.invokelater(new Runnable()) {
      public void run(){ 
            new NewJFrame().setVisible(true);
}


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnenter;
    private javax.swing.JButton btnexist;
    private javax.swing.JCheckBox chkbeg;
    private javax.swing.JCheckBox chkcroi;
    private javax.swing.JCheckBox chktoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton redcap;
    private javax.swing.JRadioButton redcoff;
    private javax.swing.JRadioButton redtea;
    private javax.swing.JTextPane subtex;
    private javax.swing.JTextPane tetex;
    private javax.swing.JTextPane textot;
    private javax.swing.JLabel txtTax;
    private javax.swing.JLabel txtTot;
    private javax.swing.JLabel txtsub;
    // End of variables declaration                   
}