/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import java.sql.*;
import Project.ConnectionProvide;

/**
 *
 * @author daudn
 */
public class DeleteQuestion extends javax.swing.JFrame {
    ConnectionProvide connectionProvide = new ConnectionProvide();
    /**
     * Creates new form DeleteQuestion
     */
    public DeleteQuestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHome = new javax.swing.JPanel();
        labelHome = new javax.swing.JLabel();
        labelDeleteQ = new javax.swing.JLabel();
        btnAddExit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        labelDelQID = new javax.swing.JLabel();
        labelDelOpt4 = new javax.swing.JLabel();
        labelDelOpt3 = new javax.swing.JLabel();
        labelDelQ = new javax.swing.JLabel();
        labelDelOpt2 = new javax.swing.JLabel();
        labelDelOpt1 = new javax.swing.JLabel();
        labelDelAns = new javax.swing.JLabel();
        txtfieldDelQ = new javax.swing.JTextField();
        txtfieldDelOpt3 = new javax.swing.JTextField();
        txtfieldDelOpt2 = new javax.swing.JTextField();
        txtfieldDelOpt1 = new javax.swing.JTextField();
        txtfieldDelOpt4 = new javax.swing.JTextField();
        txtfieldDelAns = new javax.swing.JTextField();
        btnDeleteQ = new javax.swing.JButton();
        btnUpdClear = new javax.swing.JButton();
        txtfieldDelQID = new javax.swing.JTextField();
        btnSearchQ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(150, 155));
        setUndecorated(true);

        panelHome.setBackground(new java.awt.Color(113, 141, 140));
        panelHome.setForeground(new java.awt.Color(76, 106, 114));
        panelHome.setPreferredSize(new java.awt.Dimension(1084, 555));

        labelHome.setBackground(new java.awt.Color(201, 212, 199));
        labelHome.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelHome.setForeground(new java.awt.Color(248, 249, 236));
        labelHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHome.setText("GhostDevs Quiz System");

        labelDeleteQ.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelDeleteQ.setForeground(new java.awt.Color(248, 249, 236));
        labelDeleteQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete Question.png"))); // NOI18N
        labelDeleteQ.setText("Delete Questions");

        btnAddExit.setBackground(new java.awt.Color(113, 141, 140));
        btnAddExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        btnAddExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddExitActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(248, 249, 236));

        jSeparator2.setBackground(new java.awt.Color(248, 249, 236));

        labelDelQID.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelDelQID.setForeground(new java.awt.Color(248, 249, 236));
        labelDelQID.setText("Question ID: ");

        labelDelOpt4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelDelOpt4.setForeground(new java.awt.Color(248, 249, 236));
        labelDelOpt4.setText("Option 4:");

        labelDelOpt3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelDelOpt3.setForeground(new java.awt.Color(248, 249, 236));
        labelDelOpt3.setText("Option 3:");

        labelDelQ.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelDelQ.setForeground(new java.awt.Color(248, 249, 236));
        labelDelQ.setText("Question:");

        labelDelOpt2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelDelOpt2.setForeground(new java.awt.Color(248, 249, 236));
        labelDelOpt2.setText("Option 2:");

        labelDelOpt1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelDelOpt1.setForeground(new java.awt.Color(248, 249, 236));
        labelDelOpt1.setText("Option 1:");

        labelDelAns.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelDelAns.setForeground(new java.awt.Color(248, 249, 236));
        labelDelAns.setText("Result:");

        txtfieldDelQ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtfieldDelQ.setForeground(new java.awt.Color(76, 106, 114));
        txtfieldDelQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldDelQActionPerformed(evt);
            }
        });

        txtfieldDelOpt3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtfieldDelOpt3.setForeground(new java.awt.Color(76, 106, 114));

        txtfieldDelOpt2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtfieldDelOpt2.setForeground(new java.awt.Color(76, 106, 114));

        txtfieldDelOpt1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtfieldDelOpt1.setForeground(new java.awt.Color(76, 106, 114));

        txtfieldDelOpt4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtfieldDelOpt4.setForeground(new java.awt.Color(76, 106, 114));

        txtfieldDelAns.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtfieldDelAns.setForeground(new java.awt.Color(76, 106, 114));

        btnDeleteQ.setBackground(new java.awt.Color(201, 212, 199));
        btnDeleteQ.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDeleteQ.setForeground(new java.awt.Color(76, 106, 114));
        btnDeleteQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDeleteQ.setText("Delete");
        btnDeleteQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteQActionPerformed(evt);
            }
        });

        btnUpdClear.setBackground(new java.awt.Color(201, 212, 199));
        btnUpdClear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnUpdClear.setForeground(new java.awt.Color(76, 106, 114));
        btnUpdClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear.png"))); // NOI18N
        btnUpdClear.setText("Clear");
        btnUpdClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdClearActionPerformed(evt);
            }
        });

        txtfieldDelQID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtfieldDelQID.setForeground(new java.awt.Color(76, 106, 114));
        txtfieldDelQID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldDelQIDActionPerformed(evt);
            }
        });

        btnSearchQ.setBackground(new java.awt.Color(201, 212, 199));
        btnSearchQ.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSearchQ.setForeground(new java.awt.Color(76, 106, 114));
        btnSearchQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        btnSearchQ.setText("Search");
        btnSearchQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchQMouseClicked(evt);
            }
        });
        btnSearchQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchQActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 556, Short.MAX_VALUE)
                .addComponent(btnAddExit))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDelOpt1)
                            .addComponent(labelDelOpt2)
                            .addComponent(labelDelQ)
                            .addComponent(labelDelOpt3)
                            .addComponent(labelDelOpt4)
                            .addComponent(labelDelAns)
                            .addComponent(labelDelQID))
                        .addGap(39, 39, 39)
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtfieldDelAns, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                                .addComponent(txtfieldDelOpt4)
                                .addComponent(txtfieldDelOpt3)
                                .addComponent(txtfieldDelQ)
                                .addComponent(txtfieldDelOpt2)
                                .addComponent(txtfieldDelOpt1)
                                .addGroup(panelHomeLayout.createSequentialGroup()
                                    .addComponent(txtfieldDelQID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnSearchQ)))
                            .addGroup(panelHomeLayout.createSequentialGroup()
                                .addComponent(btnDeleteQ)
                                .addGap(64, 64, 64)
                                .addComponent(btnUpdClear))))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(labelDeleteQ)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddExit)
                    .addComponent(labelHome, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(labelDeleteQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchQ)
                    .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDelQID)
                        .addComponent(txtfieldDelQID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDelQ)
                    .addComponent(txtfieldDelQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDelOpt1)
                    .addComponent(txtfieldDelOpt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDelOpt2)
                    .addComponent(txtfieldDelOpt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDelOpt3)
                    .addComponent(txtfieldDelOpt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDelOpt4)
                    .addComponent(txtfieldDelOpt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDelAns)
                    .addComponent(txtfieldDelAns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteQ)
                    .addComponent(btnUpdClear))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddExitActionPerformed
        AdminHome.open = 0;
        setVisible(false);
    }//GEN-LAST:event_btnAddExitActionPerformed

    private void txtfieldDelQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldDelQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldDelQActionPerformed

    private void btnDeleteQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteQActionPerformed
        String id = txtfieldDelQID.getText();
        try{
            Connection con = ConnectionProvide.getCon();
            PreparedStatement st = con.prepareStatement("DELETE FROM question WHERE id = ?");
            st.setString(1, id);
            st.executeUpdate();
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "Question deleted successfully!");
            setVisible(false);
            new DeleteQuestion().setVisible(true);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteQActionPerformed

    private void btnUpdClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdClearActionPerformed
        setVisible(false);
        new UpdateQuestion().setVisible(true);
    }//GEN-LAST:event_btnUpdClearActionPerformed

    private void txtfieldDelQIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldDelQIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldDelQIDActionPerformed

    private void btnSearchQMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchQMouseClicked
        
    }//GEN-LAST:event_btnSearchQMouseClicked

    private void btnSearchQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchQActionPerformed
        String id = txtfieldDelQID.getText();
        Connection con = null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/qems", "root", "Dn@0021113");
            if (con != null) {
                Statement statement = con.createStatement();
                String query = "SELECT * FROM question WHERE id = ?";
                PreparedStatement preparedStatement = con.prepareStatement(query);
                preparedStatement.setString(1, id);

                ResultSet rs = preparedStatement.executeQuery();

                if (rs.next()) {
                    txtfieldDelQ.setText(rs.getString(2));
                    txtfieldDelOpt1.setText(rs.getString(3));
                    txtfieldDelOpt2.setText(rs.getString(4));
                    txtfieldDelOpt3.setText(rs.getString(5));
                    txtfieldDelOpt4.setText(rs.getString(6));
                    txtfieldDelAns.setText(rs.getString(7));
                    txtfieldDelQ.setEditable(false);
                } else {
                    JFrame jf = new JFrame();
                    jf.setAlwaysOnTop(true);
                    JOptionPane.showMessageDialog(jf, "Question ID does not exist!");
                }

                rs.close();
                preparedStatement.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                if (con != null) {
                    System.out.println("Database Disconnected");
                    con.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnSearchQActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddExit;
    private javax.swing.JButton btnDeleteQ;
    private javax.swing.JButton btnSearchQ;
    private javax.swing.JButton btnUpdClear;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelDelAns;
    private javax.swing.JLabel labelDelOpt1;
    private javax.swing.JLabel labelDelOpt2;
    private javax.swing.JLabel labelDelOpt3;
    private javax.swing.JLabel labelDelOpt4;
    private javax.swing.JLabel labelDelQ;
    private javax.swing.JLabel labelDelQID;
    private javax.swing.JLabel labelDeleteQ;
    private javax.swing.JLabel labelHome;
    private javax.swing.JPanel panelHome;
    private javax.swing.JTextField txtfieldDelAns;
    private javax.swing.JTextField txtfieldDelOpt1;
    private javax.swing.JTextField txtfieldDelOpt2;
    private javax.swing.JTextField txtfieldDelOpt3;
    private javax.swing.JTextField txtfieldDelOpt4;
    private javax.swing.JTextField txtfieldDelQ;
    private javax.swing.JTextField txtfieldDelQID;
    // End of variables declaration//GEN-END:variables
}
