/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author daudn
 */
public class AddNewQuestion extends javax.swing.JFrame {

    /**
     * Creates new form AddNewQuestion
     */
    public AddNewQuestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHome = new javax.swing.JPanel();
        labelHome = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        btnAddExit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        labelAddQID = new javax.swing.JLabel();
        labelAddOpt4 = new javax.swing.JLabel();
        labelAddOpt3 = new javax.swing.JLabel();
        labelAddQ = new javax.swing.JLabel();
        labelAddOpt2 = new javax.swing.JLabel();
        labelAddOpt1 = new javax.swing.JLabel();
        labelAddAns = new javax.swing.JLabel();
        txtfieldAddQ = new javax.swing.JTextField();
        txtfieldAddOpt3 = new javax.swing.JTextField();
        txtfieldAddOpt2 = new javax.swing.JTextField();
        txtfieldAddOpt1 = new javax.swing.JTextField();
        txtfieldAddOpt4 = new javax.swing.JTextField();
        txtfieldAddAns = new javax.swing.JTextField();
        btnAddSave = new javax.swing.JButton();
        btnAddClear = new javax.swing.JButton();
        labelAddQIDNum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHome.setBackground(new java.awt.Color(113, 141, 140));
        panelHome.setForeground(new java.awt.Color(76, 106, 114));

        labelHome.setBackground(new java.awt.Color(201, 212, 199));
        labelHome.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelHome.setForeground(new java.awt.Color(248, 249, 236));
        labelHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHome.setText("GhosTech Quiz System");

        labelUsername.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(248, 249, 236));
        labelUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add new question.png"))); // NOI18N
        labelUsername.setText("Add New Questions");

        btnAddExit.setBackground(new java.awt.Color(113, 141, 140));
        btnAddExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        btnAddExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddExitActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(248, 249, 236));

        jSeparator2.setBackground(new java.awt.Color(248, 249, 236));

        labelAddQID.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelAddQID.setForeground(new java.awt.Color(248, 249, 236));
        labelAddQID.setText("Question ID: ");

        labelAddOpt4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelAddOpt4.setForeground(new java.awt.Color(248, 249, 236));
        labelAddOpt4.setText("Option 4:");

        labelAddOpt3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelAddOpt3.setForeground(new java.awt.Color(248, 249, 236));
        labelAddOpt3.setText("Option 3:");

        labelAddQ.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelAddQ.setForeground(new java.awt.Color(248, 249, 236));
        labelAddQ.setText("Question:");

        labelAddOpt2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelAddOpt2.setForeground(new java.awt.Color(248, 249, 236));
        labelAddOpt2.setText("Option 2:");

        labelAddOpt1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelAddOpt1.setForeground(new java.awt.Color(248, 249, 236));
        labelAddOpt1.setText("Option 1:");

        labelAddAns.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelAddAns.setForeground(new java.awt.Color(248, 249, 236));
        labelAddAns.setText("Result:");

        txtfieldAddQ.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtfieldAddQ.setForeground(new java.awt.Color(76, 106, 114));
        txtfieldAddQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldAddQActionPerformed(evt);
            }
        });

        txtfieldAddOpt3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtfieldAddOpt3.setForeground(new java.awt.Color(76, 106, 114));

        txtfieldAddOpt2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtfieldAddOpt2.setForeground(new java.awt.Color(76, 106, 114));

        txtfieldAddOpt1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtfieldAddOpt1.setForeground(new java.awt.Color(76, 106, 114));

        txtfieldAddOpt4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtfieldAddOpt4.setForeground(new java.awt.Color(76, 106, 114));

        txtfieldAddAns.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtfieldAddAns.setForeground(new java.awt.Color(76, 106, 114));

        btnAddSave.setBackground(new java.awt.Color(201, 212, 199));
        btnAddSave.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAddSave.setForeground(new java.awt.Color(76, 106, 114));
        btnAddSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        btnAddSave.setText("Save");

        btnAddClear.setBackground(new java.awt.Color(201, 212, 199));
        btnAddClear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAddClear.setForeground(new java.awt.Color(76, 106, 114));
        btnAddClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear.png"))); // NOI18N
        btnAddClear.setText("Save");

        labelAddQIDNum.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelAddQIDNum.setForeground(new java.awt.Color(248, 249, 236));
        labelAddQIDNum.setText("00");

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 983, Short.MAX_VALUE)
                .addComponent(btnAddExit))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(labelUsername))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAddOpt1)
                            .addComponent(labelAddOpt2)
                            .addComponent(labelAddQ)
                            .addComponent(labelAddOpt3)
                            .addComponent(labelAddOpt4)
                            .addComponent(labelAddAns)
                            .addComponent(labelAddQID))
                        .addGap(39, 39, 39)
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelHomeLayout.createSequentialGroup()
                                .addComponent(btnAddSave)
                                .addGap(63, 63, 63)
                                .addComponent(btnAddClear))
                            .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtfieldAddAns, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                                .addComponent(txtfieldAddOpt4)
                                .addComponent(txtfieldAddOpt3)
                                .addComponent(txtfieldAddQ)
                                .addComponent(txtfieldAddOpt2)
                                .addComponent(txtfieldAddOpt1))
                            .addComponent(labelAddQIDNum))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddExit)
                    .addComponent(labelHome, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(labelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddQID)
                    .addComponent(labelAddQIDNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddQ)
                    .addComponent(txtfieldAddQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddOpt1)
                    .addComponent(txtfieldAddOpt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddOpt2)
                    .addComponent(txtfieldAddOpt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddOpt3)
                    .addComponent(txtfieldAddOpt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddOpt4)
                    .addComponent(txtfieldAddOpt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddAns)
                    .addComponent(txtfieldAddAns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSave)
                    .addComponent(btnAddClear))
                .addGap(0, 244, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddExitActionPerformed

    private void txtfieldAddQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldAddQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldAddQActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddClear;
    private javax.swing.JButton btnAddExit;
    private javax.swing.JButton btnAddSave;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelAddAns;
    private javax.swing.JLabel labelAddOpt1;
    private javax.swing.JLabel labelAddOpt2;
    private javax.swing.JLabel labelAddOpt3;
    private javax.swing.JLabel labelAddOpt4;
    private javax.swing.JLabel labelAddQ;
    private javax.swing.JLabel labelAddQID;
    private javax.swing.JLabel labelAddQIDNum;
    private javax.swing.JLabel labelHome;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPanel panelHome;
    private javax.swing.JTextField txtfieldAddAns;
    private javax.swing.JTextField txtfieldAddOpt1;
    private javax.swing.JTextField txtfieldAddOpt2;
    private javax.swing.JTextField txtfieldAddOpt3;
    private javax.swing.JTextField txtfieldAddOpt4;
    private javax.swing.JTextField txtfieldAddQ;
    // End of variables declaration//GEN-END:variables
}
