import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class AdminHome extends javax.swing.JFrame {
    public static int open = 0;
    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        menubarAdmin = new javax.swing.JMenuBar();
        menuAddQuestions = new javax.swing.JMenu();
        menuUpdateQuestion = new javax.swing.JMenu();
        menuDelQuestions = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuAllQuestions = new javax.swing.JMenu();
        menuResults = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(47, 72, 88));

        jPanel1.setBackground(new java.awt.Color(113, 141, 140));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        menubarAdmin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Admin Home Page", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 24), new java.awt.Color(76, 106, 114))); // NOI18N

        menuAddQuestions.setBackground(new java.awt.Color(113, 141, 140));
        menuAddQuestions.setForeground(new java.awt.Color(201, 212, 199));
        menuAddQuestions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add new question.png"))); // NOI18N
        menuAddQuestions.setText("Add New Question");
        menuAddQuestions.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        menubarAdmin.add(menuAddQuestions);

        menuUpdateQuestion.setBackground(new java.awt.Color(113, 141, 140));
        menuUpdateQuestion.setForeground(new java.awt.Color(201, 212, 199));
        menuUpdateQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Update Question.png"))); // NOI18N
        menuUpdateQuestion.setText("Update Questions");
        menuUpdateQuestion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        menubarAdmin.add(menuUpdateQuestion);

        menuDelQuestions.setBackground(new java.awt.Color(113, 141, 140));
        menuDelQuestions.setForeground(new java.awt.Color(201, 212, 199));
        menuDelQuestions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete Question.png"))); // NOI18N
        menuDelQuestions.setText("Delete Questions");
        menuDelQuestions.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jMenu2.setText("jMenu2");
        menuDelQuestions.add(jMenu2);

        menubarAdmin.add(menuDelQuestions);

        menuAllQuestions.setBackground(new java.awt.Color(113, 141, 140));
        menuAllQuestions.setForeground(new java.awt.Color(201, 212, 199));
        menuAllQuestions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all questions.png"))); // NOI18N
        menuAllQuestions.setText("All Questions");
        menuAllQuestions.setToolTipText("");
        menuAllQuestions.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        menubarAdmin.add(menuAllQuestions);

        menuResults.setBackground(new java.awt.Color(113, 141, 140));
        menuResults.setForeground(new java.awt.Color(201, 212, 199));
        menuResults.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all student result.png"))); // NOI18N
        menuResults.setText("Student Results");
        menuResults.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        menubarAdmin.add(menuResults);

        menuLogout.setBackground(new java.awt.Color(113, 141, 140));
        menuLogout.setForeground(new java.awt.Color(201, 212, 199));
        menuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logout.png"))); // NOI18N
        menuLogout.setText("Logout");
        menuLogout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
        });
        menubarAdmin.add(menuLogout);

        menuExit.setBackground(new java.awt.Color(113, 141, 140));
        menuExit.setForeground(new java.awt.Color(201, 212, 199));
        menuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        menuExit.setText("Exit");
        menuExit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        menuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuExitMouseClicked(evt);
            }
        });
        menubarAdmin.add(menuExit);

        setJMenuBar(menubarAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        JFrame logout = new JFrame();
        logout.setAlwaysOnTop(true);
        int a = JOptionPane.showConfirmDialog(logout, "Do you really want to logout?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0){
            setVisible(false);
            new LoginPage().setVisible(true);
        }
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void menuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuExitMouseClicked
        JFrame exit = new JFrame();
        exit.setAlwaysOnTop(true);
        int a = JOptionPane.showConfirmDialog(exit, "Do you really want to close the Application?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_menuExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAddQuestions;
    private javax.swing.JMenu menuAllQuestions;
    private javax.swing.JMenu menuDelQuestions;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuResults;
    private javax.swing.JMenu menuUpdateQuestion;
    private javax.swing.JMenuBar menubarAdmin;
    // End of variables declaration//GEN-END:variables
}
